model = "gpt-5.1-codex"
model_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[features]
web_search_request = true

streamable_shell = true          # enable the streamable exec tool
experimental_sandbox_command_assessment	= true
unified_exec = false
apply_patch_freeform = true
ghost_commit = true

# Streamable HTTP requires the experimental rmcp client
rmcp_client = true

[tui]
# Send desktop notifications when approvals are required or a turn completes.
# Defaults to false.
notifications = true

[projects."/home/bcherrington/Projects/Webstorm/activitywatcher-mcp"]
trust_level = "trusted"

[projects."/home/bcherrington/Projects/PyCharm/activitywatch/aw-import-ical"]
trust_level = "trusted"

[projects."/home/bcherrington/Projects/Auriora/repo-template"]
trust_level = "trusted"

[projects."/home/bcherrington/Projects/Auriora/TimeLocker"]
trust_level = "trusted"

[projects."/home/bcherrington/Projects/Bruce-5560"]
trust_level = "trusted"

#[mcp_servers.activitywatcher]
#url = "http://localhost:3000/mcp"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_TOKEN"

[mcp_servers.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]

[mcp_servers.sequentialthinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.tavily]
url = "https://mcp.tavily.com/mcp/?tavilyApiKey=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"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-3d725aad-8982-405d-a0fe-6ccd0bdfcecc"]

#[mcp_servers.everthing]
#command = "npx"
#args = ["-y", "@modelcontextprotocol/server-everything"]

[notice]
hide_full_access_warning = true
hide_gpt5_1_migration_prompt = true


